### PR TITLE
Create ptracking python package

### PR DESCRIPTION
**Pull request by abulavin**
- Move fetching code to `ptracking.fetch`
- reorganise repository as python package

Lots of changes here so don't worry about reviewing all - there are definitely things to be improved

### CODE REVIEW

**Review by MihneaLungu — APPROVED** [review]

**Comment by abulavin** [comment]
[package config](https://trello.com/c/r8cvpL1i/45-package-config)

**Comment by abulavin** [comment]
[Modify scraping script to insert straight into DB](https://trello.com/c/jZsQWpvQ/39-modify-scraping-script-to-insert-straight-into-db)

**Comment by abulavin** [comment]
[Write unit tests for scraping](https://trello.com/c/SjNS1PL1/42-write-unit-tests-for-scraping)

**Comment by abulavin** [comment]
[Reorganise the repository as python package](https://trello.com/c/dZ40PQiG/41-reorganise-the-repository-as-python-package)

**Comment by abulavin** [comment]
[Change the cron job to use the new scraping script](https://trello.com/c/FnqVUpfV/48-change-the-cron-job-to-use-the-new-scraping-script)

**Pull request merged**
